import { Bot, InputFile } from 'grammy';
import prisma from '../db/client.js';
import { processAgentMessage } from '../agent/agent.js';
import { clearDraftBill } from '../services/billing.js';

export function createTelegramBot(token: string) {
  const bot = new Bot(token);

  // Idempotency Middleware using ProcessedUpdate
  bot.use(async (ctx, next) => {
    const updateId = String(ctx.update.update_id);

    // Check if already processed
    const existing = await prisma.processedUpdate.findUnique({
      where: { telegramUpdateId: updateId },
    });

    if (existing) {
      console.log(`[Idempotency] Skipping duplicate update_id: ${updateId}`);
      return;
    }

    // Process update
    await next();

    // Mark as processed
    try {
      await prisma.processedUpdate.create({
        data: { telegramUpdateId: updateId },
      });
    } catch (err) {
      // Ignore unique constraint error if concurrently inserted
    }
  });

  // /start command
  bot.command('start', async (ctx) => {
    await ctx.reply(
      `👋 *Welcome to Supermarket Ops Agent!*\n\n` +
        `I am your AI Store Operations Assistant. You can speak to me naturally to manage inventory, billing, Khata credit, sales analytics, and generate PDF invoices & PPTX reports.\n\n` +
        `*Try commands like:*\n` +
        `• "How much Aashirvaad atta do we have?"\n` +
        `• "Add 20 packets of Maggi."\n` +
        `• "Bill 2 atta and 3 Maggi for Ravi."\n` +
        `• "Ravi wants it on credit."\n` +
        `• "Generate today's sales report."\n` +
        `• "Remember that I prefer UPI payments."\n\n` +
        `Type /new to start a fresh bill draft.`,
      { parse_mode: 'Markdown' }
    );
  });

  // /new command (resets draft bill session without touching preferences)
  bot.command('new', async (ctx) => {
    const telegramUserId = String(ctx.from?.id || 'default_user');
    await clearDraftBill(telegramUserId);
    await ctx.reply('✨ *Draft bill reset!* Starting a new billing session. Your stored preferences are intact.', {
      parse_mode: 'Markdown',
    });
  });

  // Natural Language Messages
  bot.on('message:text', async (ctx) => {
    const telegramUserId = String(ctx.from?.id || 'default_user');
    const userMessage = ctx.message.text;

    // Send typing indicator
    await ctx.replyWithChatAction('typing');

    try {
      const agentResult = await processAgentMessage(telegramUserId, userMessage);

      if (agentResult.text) {
        await ctx.reply(agentResult.text);
      }

      // Deliver documents if generated by tools
      for (const fileObj of agentResult.filesToSend) {
        await ctx.replyWithChatAction('upload_document');
        await ctx.replyWithDocument(new InputFile(fileObj.filePath), {
          caption: fileObj.fileType === 'pdf' ? '📄 Tax Invoice PDF' : '📊 Sales Analysis Presentation PPTX',
        });
      }
    } catch (err: any) {
      console.error('[Bot Error]', err);
      await ctx.reply(`⚠️ *Error:* ${err.message || 'An unexpected error occurred while processing your request.'}`, {
        parse_mode: 'Markdown',
      });
    }
  });

  return bot;
}
